name: Create-edit-view-file
on: 
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create file
        run: touch hello.txt
  Write:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Write into file
        run: |
          echo "Hello Word" > hello.txt
          cat hello.txt
  View:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: View hello.txt
        run: cat hello.txt
    
        
        
